name: Set up languages
description: Set up ruby, javascript, and dependencies
runs:
  using: composite
  steps:
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        # bundler-cache automatically installs gems
        bundler-cache: true
        cache-version: 1

    - name: Set up node
      uses: actions/setup-node@v2
      with:
        node-version: '16.13.1'
        cache: 'yarn'
    - name: Install yarn dependencies
      shell: bash
      run: yarn install --frozen-lockfile
