version: "3.2"
services:
  web:
    build:
      context: .
    user: ${CURRENT_USER:-root}
    networks:
      - test-at-home
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: ci
      DATABASE_URL: postgres://circleci:notasecret@db:5432/test_at_home_ci
      RAILS_MASTER_KEY: $RAILS_MASTER_KEY
  db:
    image: cimg/postgres:12.9
    environment:
      POSTGRES_USER: circleci
      POSTGRES_DB: test_at_home_ci
      POSTGRES_PASSWORD: notasecret
    networks:
      - test-at-home
networks:
  test-at-home:
