module StatesHelper
  def us_states
    [
      ["AL - Alabama", "AL"],
      ["AK - Alaska", "AK"],
      ["AS - American Samoa", "AS"],
      ["AZ - Arizona", "AZ"],
      ["AR - Arkansas", "AR"],
      ["CA - California", "CA"],
      ["CO - Colorado", "CO"],
      ["CT - Connecticut", "CT"],
      ["DE - Delaware", "DE"],
      ["DC - District of Columbia", "DC"],
      ["FL - Florida", "FL"],
      ["GA - Georgia", "GA"],
      ["GU - Guam", "GU"],
      ["HI - Hawaii", "HI"],
      ["ID - Idaho", "ID"],
      ["IL - Illinois", "IL"],
      ["IN - Indiana", "IN"],
      ["IA - Iowa", "IA"],
      ["KS - Kansas", "KS"],
      ["KY - Kentucky", "KY"],
      ["LA - Louisiana", "LA"],
      ["ME - Maine", "ME"],
      ["MD - Maryland", "MD"],
      ["MA - Massachusetts", "MA"],
      ["MI - Michigan", "MI"],
      ["MN - Minnesota", "MN"],
      ["MS - Mississippi", "MS"],
      ["MO - Missouri", "MO"],
      ["MT - Montana", "MT"],
      ["NE - Nebraska", "NE"],
      ["NV - Nevada", "NV"],
      ["NH - New Hampshire", "NH"],
      ["NJ - New Jersey", "NJ"],
      ["NM - New Mexico", "NM"],
      ["NY - New York", "NY"],
      ["NC - North Carolina", "NC"],
      ["ND - North Dakota", "ND"],
      ["MP - Northern Mariana Islands", "MP"],
      ["OH - Ohio", "OH"],
      ["OK - Oklahoma", "OK"],
      ["OR - Oregon", "OR"],
      ["PA - Pennsylvania", "PA"],
      ["PR - Puerto Rico", "PR"],
      ["RI - Rhode Island", "RI"],
      ["SC - South Carolina", "SC"],
      ["SD - South Dakota", "SD"],
      ["TN - Tennessee", "TN"],
      ["TX - Texas", "TX"],
      ["UM - United States Minor Outlying Islands", "UM"],
      ["UT - Utah", "UT"],
      ["VT - Vermont", "VT"],
      ["VI - Virgin Islands", "VI"],
      ["VA - Virginia", "VA"],
      ["WA - Washington", "WA"],
      ["WV - West Virginia", "WV"],
      ["WI - Wisconsin", "WI"],
      ["WY - Wyoming", "WY"],
      ["AA - Armed Forces Americas", "AA"],
      ["AE - Armed Forces Africa", "AE"],
      ["AE - Armed Forces Canada", "AE"],
      ["AE - Armed Forces Europe", "AE"],
      ["AE - Armed Forces Middle East", "AE"],
      ["AP - Armed Forces Pacific", "AP"]
    ]
  end
end
