name: Set up project with database
description: Setup Ruby, Javascript, and load the database schema into a running postgres db
inputs:
  rails_env:
    description: RAILS_ENV to set. Defaults to test
    required: false
    default: test
  database_url:
    description: DATABASE_URL to set
    required: false
    default: postgres://pangolin:postgres@localhost:5432/pangolin_test
outputs:
  database_url:
    value: ${{ inputs.database_url }}
runs:
  using: composite
  steps:
    - name: Set up Ruby & Javascript
      uses: ./.github/actions/setup-languages

    - name: Set up database
      env:
        RAILS_ENV: ${{ inputs.rails_env }}
        DATABASE_URL: ${{ inputs.database_url }}
      shell: bash
      run: bundle exec rake db:schema:load
